version: '3.8'
services:
  coineus-frontend:
    image: "safderun/coineus-frontend:latest"
    container_name: coineus-frontend
    networks:
      - coineus_network
    ports:
      - 80:80
networks:
    coineus_network:
      driver: bridge