version: '3.8'

services:
  coineus-frontend-jenkins:
    image: "safderun/coineus-frontend:${TAG}"
    container_name: coineus-frontend
    networks:
      - coineus_network
    ports:
      - 80:80
      
networks:
    coineus_network:
      external: true
